### ISSUE TITLE
German Rules out of Date? 

### ISSUE THREAD

**Issue by Ein-Tim** [timokoenig/eu-dcc-rules#1]
https://timokoenig.github.io/eu-dcc-rules/?country=DE&rule=RR-DE-0002 states that the positive test is not allowed to be older than 180 days, however, in the CWA and on https://distribution.dcc-rules.de/rules/DE/71b10c1d78bcdd9e0f27afb6368a4a086d6d558616a1cd890765f6b1178d3325 it says that the positive test is not allowed to be older than 90 days.

**Comment by timokoenig** [comment]
eu-dcc-rules caches the rules to reduce the load on the server and to have a history of the rules thanks to git. I have a Github Action that runs once a day (around 1am) to fetch the newest rules.

I guess Germany updated the rules today, meaning tonight these rules will get updated for this project as well.

**Comment by Ein-Tim** [comment]
I already thought so, thanks for confirming, Timo!

**Comment by Ein-Tim** [comment]
@timokoenig Seems like the script did not run? I still see that the site was last updated at 22.02.22?

**Comment by timokoenig** [comment]
hm let me check

**Comment by timokoenig** [comment]
@Ein-Tim just updated the rules manually.

There is a problem with the Github Action. I will investigate later

**Comment by timokoenig** [comment]
Also found another issue because DE rules now have two rules with the same Identifier. In general they should not do this but anyways I will fix it so both get displayed correctly

**Comment by Ein-Tim** [comment]
Thanks @timokoenig!

**Comment by timokoenig** [comment]
@Ein-Tim please see https://github.com/Digitaler-Impfnachweis/certification-apis/issues/230

**Comment by timokoenig** [comment]
The fix from earlier helped. Everything is working fine again
