### ISSUE TITLE
Add domestic rules of Germany?

### ISSUE THREAD

**Issue by Ein-Tim** [timokoenig/eu-dcc-rules#2]
Is it planned to add the domestic rules of Germany to this page?

**Comment by timokoenig** [comment]
I'm not sure what Taddeo is, but I will see what I can do to add domestic rules and maybe the booster notification rules as well

**Comment by Ein-Tim** [comment]
@timokoenig 

Taddeo was a typo, sorry.

**Comment by timokoenig** [comment]
@Ein-Tim ok 😂

**Comment by timokoenig** [comment]
Done and deployed. You can now select EU Entry Rules, DE Domestic Rules, and DE Booster Notification Rules.
